CREATE DATABASE IF NOT EXISTS tienda;

USE tienda;

CREATE TABLE IF NOT EXISTS productos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255),
	precio DECIMAL(7,2),
	stock INT
);

CREATE TABLE IF NOT EXISTS clientes (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255),
	email VARCHAR(255),
	telefono VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS pedidos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_cliente INT,
	id_producto INT,
	cantidad INT,
	fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
	FOREIGN KEY (id_producto) REFERENCES productos(id) ON DELETE CASCADE
);