CREATE DATABASE IF NOT EXISTS tienda;

USE tienda;

CREATE TABLE IF NOT EXISTS productos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255),
	precio DECIMAL(7,2),
	stock INT
);

CREATE TABLE IF NOT EXISTS pedidos(
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_cliente INT,
	FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
	cantidad INT,
	fecha DATE DEFAULT (CURRENT_DATE)
);