CREATE DATABASE IF NOT EXISTS tienda;

USE tienda;

CREATE TABLE IF NOT EXISTS productos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255),
	precio DECIMAL(7,2),
	stock INT
);

CREATE TABLE IF NOT EXISTS clientes (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255),
	email VARCHAR(255),
	telefono VARCHAR(20)
);